site_name: MDS-2020-2-G6
site_description: Repositório da disciplina de MDS
repo_url: https://github.com/fga-eps-mds/MDS-2020-2-G6 

theme:
    name: material

plugins:
    - search

nav:
    - Home: "index.md"
    - Documento de Visão: "Documento_de_visao.md"
    - Documento de Metodologia: "Documento_metodologia.md"
    - Documento de Arquitetura: "Documento_de_arquitetura.md"
    - Sprints:
        - Sprint 0:
            - Planning: "sprints/sprint_0/Planning_sprint_0.md"
            - Review: "sprints/sprint_0/Review_sprint_0.md"
        - Sprint 1:
            - Planning: "sprints/sprint_1/Planning_sprint_1.md"
            - Review: "sprints/sprint_1/Review_sprint_1.md"
