site_name: Hortum
site_description: Repositório do Projeto Hortum
repo_url: https://github.com/fga-eps-mds/2020.2-Hortum 
dev_addr: '127.0.0.1:8080'

theme:
    name: material

plugins:
    - search

nav:
    - Home: "index.md"
    - Documento de Visão: "Documento_de_visao.md"
    - Documento de Metodologia: "Documento_metodologia.md"
    - Documento de Arquitetura: "Documento_de_arquitetura.md"
    - Protótipo: "Prototipo.md"
    - Guia de Estilo e Manual de Identidade Visual: "Guia_de_estilo_e_identidade_visual.md"
    - Product Backlog: "Product_Backlog.md"
    - Canvas: "Canvas.md"
    - Contribuição:
        - Como contribuir: "CONTRIBUTING.md"
        - Política de Contribuição: "Politica_de_Contribuicao.md"
        - Código de Conduta: "CODE_OF_CONDUCT.md"
    - Sprints:
        - Sprint 0:
            - Planning: "sprints/sprint_0/Planning_sprint_0.md"
            - Review: "sprints/sprint_0/Review_sprint_0.md"
        - Sprint 1:
            - Planning: "sprints/sprint_1/Planning_sprint_1.md"
            - Review: "sprints/sprint_1/Review_sprint_1.md"
        - Sprint 2:
            - Planning: "sprints/sprint_2/Planning_sprint_2.md"
            - Review: "sprints/sprint_2/Review_sprint_2.md"
        - Sprint 3:
            - Planning: "sprints/sprint_3/Planning_sprint_3.md"
            - Review: "sprints/sprint_3/Review_sprint_3.md"
        - Sprint 4:
            - Planning: "sprints/sprint_4/Planning_sprint_4.md"
            - Review: "sprints/sprint_4/Review_sprint_4.md"
