name: Teste CI
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Subindo ambiente de teste
        run: docker-compose up -d --build
      - name: Rodando teste
        run: docker exec 20202-hortum_web_1 bash -c "python manage.py test"
      - run: pip install mkdocs-material
      - name: Atualizando github pages
        run: mkdocs gh-deploy --force